processor:
  # RE2 regular expressions describing types that should be excluded from the generated documentation.
  ignoreTypes:
    - "(QuestDB(Snapshot|SnapshotSchedule)?)List$"
  # RE2 regular expressions describing type fields that should be excluded from the generated documentation.
  ignoreFields:
    #- "status$"
    - "TypeMeta$"
render:
  # Version of Kubernetes to use when generating links to Kubernetes API documentation.
  kubernetesVersion: 1.25
  # Generate better link for known types
  knownTypes:
    - name: Quantity
      package: k8s.io/apimachinery/pkg/api/resource
      link: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/
