---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-questdb-io-v1beta1-questdb
  failurePolicy: Fail
  name: mquestdb.kb.io
  rules:
  - apiGroups:
    - crd.questdb.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - questdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-questdb-io-v1beta1-questdbsnapshot
  failurePolicy: Fail
  name: mquestdbsnapshot.kb.io
  rules:
  - apiGroups:
    - crd.questdb.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - questdbsnapshots
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-questdb-io-v1beta1-questdb
  failurePolicy: Fail
  name: vquestdb.kb.io
  rules:
  - apiGroups:
    - crd.questdb.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - questdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-questdb-io-v1beta1-questdbsnapshot
  failurePolicy: Fail
  name: vquestdbsnapshot.kb.io
  rules:
  - apiGroups:
    - crd.questdb.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - questdbsnapshots
  sideEffects: None
