# permissions for end users to view questdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: questdb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: questdb-operator-v4
    app.kubernetes.io/part-of: questdb-operator-v4
    app.kubernetes.io/managed-by: kustomize
  name: questdb-viewer-role
rules:
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbs/status
  verbs:
  - get
