---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbs/finalizers
  verbs:
  - update
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbsnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbsnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbsnapshotschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbsnapshotschedules/finalizers
  verbs:
  - update
- apiGroups:
  - crd.questdb.io
  resources:
  - questdbsnapshotschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - questdbsnapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
