# permissions for end users to edit snapshotschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: snapshotschedule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: questdb-operator
    app.kubernetes.io/part-of: questdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: snapshotschedule-editor-role
rules:
- apiGroups:
  - crd.questdb.io
  resources:
  - snapshotschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.questdb.io
  resources:
  - snapshotschedules/status
  verbs:
  - get
