apiVersion: crd.questdb.io/v1beta1
kind: QuestDBSnapshotSchedule
metadata:
  labels:
    app.kubernetes.io/name: questdbsnapshotschedule
    app.kubernetes.io/instance: questdbsnapshotschedule-sample
    app.kubernetes.io/part-of: questdb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: questdb-operator
  name: questdbsnapshotschedule-sample
spec:
  # TODO(user): Add fields here
