---
apiVersion: v1
kind: Secret
metadata:
  name: ilp-secret
  namespace: default
  annotations:
    questdb.crd.questdb.io/name: questdb-sample
    questdb.crd.questdb.io/secret-type: ilp
type: Opaque
stringData:
  auth.json: |
    {
      "x": "XWAfUtVHBmZ47K7Tqp0iXX2Lhe_-y0UtFGpqjlkIaTk",
      "y": "jmle-xIu3PWUv-zCtUZZIUyF9Rf4wzIK9S0VbB4N6z0",
      "kid": "admin",
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
  namespace: default
  annotations:
    questdb.crd.questdb.io/name: questdb-sample
    questdb.crd.questdb.io/secret-type: psql
type: Opaque
stringData:
  QDB_PG_USER: my-user
  QDB_PG_PASSWORD: my-password
