---
apiVersion: v1
kind: Secret
metadata:
  name: ilp-secret
  namespace: default
  annotations:
    questdb.crd.questdb.io/name: questdb-sample
    questdb.crd.questdb.io/secret-type: ilp
type: Opaque
stringData:
  d: "WKTreldZ2WGexogKx0nSlquF-LGLF2gDW8AUZz_-q-s"
  x: "2gQDGeMb7NCtHPVhv9O7yIOgtSO9HteC71RfLWlDvwQ"
  y: "3rPZ1MeeZ_vmu0Js6CICm3SkUNuxMyVcL3T0i1KCurg"
  crv: "P-256"
  kid: "admin"
  kty: "EC"
---
apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
  namespace: default
  annotations:
    questdb.crd.questdb.io/name: questdb-sample
    questdb.crd.questdb.io/secret-type: psql
type: Opaque
stringData:
  QDB_PG_USER: my-user
  QDB_PG_PASSWORD: my-password
